name: phrasely-ci
channels:
  - conda-forge
  - defaults
channel_priority: strict

dependencies:
  - python=3.10
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn=1.5.*
  - hdbscan
  - umap-learn>=0.5.6
  - pyarrow>=15.0
  - matplotlib>=3.8
  - tqdm
  - psutil
  - joblib
  - pyyaml
  - pytest
  - flake8
  - mypy
  - jupyterlab
  - sentence-transformers=3.0.*
  - pip:
      - rapidfuzz>=3.6.1
